### PR TITLE
Added links to help (README.md) and AutoPkgr home (lindegroup.com/autopk...

### PR DESCRIPTION
**Pull request by futureimperfect**
...gr) in the Help menu.

I couldn't test this because of a Cocoapods issue with mailcore2, (@eahrold, the fix you sent Elliot and I didn't seem to work).

### CODE REVIEW

**Comment by eahrold** [comment]
@futureimperfect 
Did you do 
`cd ~/.cocoapods/repos/master/ ; git reset --hard origin/master`

if not where does 
` pod update --verbose` fail?

**Comment by futureimperfect** [comment]
Ah gotcha. I was doing `pod install`. `pod update` works.

Thanks!

**Comment by homebysix** [comment]
I can't build this branch. I get this error:

screen shot 2015-04-07 at 8 00 10 am

I tried removing the AutoPkgr-* folders from DerivedData, clean build, but still didn't work.

**Comment by homebysix** [comment]
Actually, I can't build either this branch or the 1.2.2-beta branch. I'm guessing it's a cocoapods issue. I'll send you details by email.

**Comment by homebysix** [comment]
OK, finally got the build working. Had to downgrade to CocoaPods 0.35.0. Thanks to @eahrold for figuring that out.

This branch works well for me. Merging in.

**Pull request merged**
