### PR TITLE
Use BSD kinfo_proc to determine if an autopkg instance is running

### PR DESCRIPTION
**Pull request by eahrold**
Now uses [BSDProcessInfo class](https://github.com/eahrold/BSDProcessInfo) rather than string parsing.

### CODE REVIEW

**Comment by homebysix** [comment]
Won't build. Can you check this out?
screen shot 2015-07-24 at 8 00 30 am

**Comment by eahrold** [comment]
Ok so two things to try.

1) Navigate to the BSDProcessInfo.m file and then uncheck / recheck the "Target Membership" checkbox for AutoPkgr. Clean and rebuild.

screen shot 2015-07-24 at 10 08 09 am

If that doesn't work look at the "Compiled Sources" in the "Build Phase" section make sure it's there and not red. Also see that it's not listed twice. 

screen shot 2015-07-24 at 10 24 05 am

**Comment by homebysix** [comment]
Did both things, but neither worked. Compile sources looks the same as yours. Weird.

**Comment by eahrold** [comment]
I found it. I didn't commit the header import. 
It should be fixed now.

**Comment by homebysix** [comment]
:hand: High five. That fixed it.

**Comment by eahrold** [comment]
:hand: back at ya!

**Pull request merged**
