### PR TITLE
VirusTotalAnalyzer integration

### LINKED ISSUE #503: Easy GUI configuration of VirusTotalAnalyzer
Today I learned that Hannes has been working on a very interesting and useful AutoPkg processor called [VirusTotalAnalyzer](https://github.com/hjuutilainen/autopkg-virustotalanalyzer). It runs as a post-processor and checks downloaded files against the VirusTotal threat database.

If we incorporate the installation and configuration of VirusTotalAnalyzer into AutoPkgr, it would be a great way to reduce friction and encourage administrators to use the processor.

It would be pretty straightforward, very similar to what we did for MacPatchImporter.
- Add the repo.
- Add the post-processor to the existing list of post-processors.
- Provide fields in which the defaults settings could be configured.

Thoughts?

### PR DESCRIPTION
**Pull request by homebysix**
I'm resurrecting this PR in preparation for adding the [VirusTotalAnalyzer](https://github.com/hjuutilainen/autopkg-virustotalanalyzer) integration into AutoPkgr.

In order to merge this in, we'll want the following features working. I'll keep the list up to date as we confirm things work, and once everything is checked we can merge.

- [x] A button in the __Folders & Integration__ tab that says __Install VirusTotalAnalyzer__. When you click the button, two things happen:
    - [x] This command runs: `autopkg repo-add https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git`
    - [x] `io.github.hjuutilainen.VirusTotalAnalyzer/VirusTotalAnalyzer` is appended to the `PostProcessors` list.
- [x] After that repo is added, the button changes to __Configure VirusTotalAnalyzer__. Clicking this button presents an interface for editing the [configurable options listed here](https://github.com/hjuutilainen/autopkg-virustotalanalyzer#configurable-options).
    - [x] A radio button with two options: "default API key" and "custom API key." It's set to "default API key" by default, but when switched to "custom API key" a text field for pasting the API key becomes editable. This field connects with `VIRUSTOTAL_API_KEY`.
    - [x] A "pause between scans" text field that accepts integers ≥ 0, which connects with `VIRUSTOTAL_SLEEP_SECONDS`.
    - [x] An "always scan downloads" checkbox that connects with `VIRUSTOTAL_ALWAYS_REPORT`.
    - [x] An "automatically submit" checkbox that connects with `VIRUSTOTAL_AUTO_SUBMIT`. When checked, it enables a "maximum file size" field that accepts integers > 0, which connects to `VIRUSTOTAL_AUTO_SUBMIT_MAX_SIZE`.
    - [ ] Optional - The "maximum file size" field would have a pop-up menu after it allowing the user to select among KB, MB, and GB, and AutoPkgr would do the math to convert this to bytes before writing the `VIRUSTOTAL_AUTO_SUBMIT_MAX_SIZE ` setting.
- [x] The "Uninstall" feature runs `autopkg repo-delete https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git`. It also removes VirusTotalAnalyzer from the post-processor list.
- [x] Some mechanism for notifying when updates are available. Since VirusTotalAnalyzer has its own repo, we can simply check whether that repo needs an update and display a green/yellow indicator as necessary. Clicking the Update button will simply run `autopkg repo-update https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git`.
- [x] After an AutoPkg run, VirusTotalAnalyzer summary results are included in the email notification.

Closes #503.

### CODE REVIEW

**Comment by eahrold** [comment]
@homebysix I just checked off a few of these, but they need testing, since I haven't really played around with VTA.

**Comment by homebysix** [comment]
Nice, thanks! I gave up trying to figure out the right `autoPkgDomainObject` syntax.

Looks like the UI settings in the "Configure VirusTotalAnalyzer" panel don't "stick" the second time you open them. (Even though they do set the correct values in the AutoPkg preference file.)

**Comment by homebysix** [comment]
The only thing remaining is this:
> The "Uninstall" feature removes the defaults values associated with VirusTotalAnalyzer

If you give me the `defaults delete` equivalent, I can probably make that happen.

**Comment by eahrold** [comment]
It looks like you already did this
https://github.com/lindegroup/autopkgr/blob/f3d8294451b53719477a87b6581c222c2ff312ab/AutoPkgr/Models/Integrations/LGVirusTotalAnalyzerIntegration.m#L69-82

**Comment by homebysix** [comment]
That block sets the values back to defaults, but it doesn't actually delete them from the preferences file as far as I can see.

**Comment by eahrold** [comment]
Gotchya… 
Just setting them to nil should do the trick.

**Comment by homebysix** [comment]
Nope, it doesn't like that.

screen shot 2016-05-24 at 8 13 29 am

Still learning my Obj-C basics.

**Comment by eahrold** [comment]
Right, right, right….

Two ways. copy the respective set autpkgr domain command from the defaults method, and paste those there setting null as the value. Or change the defaults to accept an NSNumber rather than an NSInteger and update everywhere the defaults are set wrapping the integer like this   @(2)

**Comment by homebysix** [comment]
That works for the NSIntegers, but what about the booleans?

**Comment by homebysix** [comment]
Resetting the VirusTotalAnalyzer preferences to their defaults upon uninstallation is sufficient for now. I may revisit this later, because there's a case to be made for why preference settings are "user data" and shouldn't be altered upon uninstallation. But that's a broader topic.

This PR is good to go! Thanks @eahrold!

**Comment by eahrold** [comment]
Sorry for the late reply but @(YES) is an NSNumber too.

**Comment by eahrold** [comment]
@homebysix sorry for the late response here but @(YES) is an NSNumber too

**Pull request merged**
