### PR TITLE
10.8 hotfix

### PR DESCRIPTION
**Pull request by eahrold**
Addresses a number of potential issues possible causing instability on 10.8 when accessing system keychain in rapid succession.

### CODE REVIEW

**Comment by homebysix** [comment]
@eahrold Do you think this is a super urgent one? I could wrap up a 1.3.1 tomorrow or Friday that includes this and the other recent bug fixes.

**Comment by eahrold** [comment]
Yes, this issue is probably my biggest concern since I was causing my machine's network to crash. According to this https://developer.apple.com/library/mac/documentation/Security/Reference/certifkeytrustservices/ 10.7+ all those KC calls should be thread safe and reentrant, but I've got a sneaking suspicion that it may not be 100% true. 

I've been running with these changes for 3 days now and the issue hasn't reoccurred.

**Comment by homebysix** [comment]
So far, one little blip on my fresh 10.8 VM.

1. Installed AutoPkgr.
2. Used AutoPkgr to install Git and AutoPkg:
    screen shot 2015-07-29 at 10 57 39 am
3. Tried to add default repo, and got this:
    screen shot 2015-07-29 at 10 57 33 am


Quitting and relaunching AutoPkgr solved the issue, and I was subsequently able to add the default repo with no issues.

**Comment by eahrold** [comment]
@homebysix can you try again, it may have just been a glitch. I just went over the code and it definitely should be setting the `com.github.autopkg GIT_PATH` key [10.8-hotfix ... LGGitIntegration.m#L122-L126](https://github.com/lindegroup/autopkgr/blob/10.8-hotfix/AutoPkgr/Models/Integrations/LGGitIntegration.m#L122-L126). Also this behavior shouldn't be specific to this branch.

So right after you install do a defaults read and see if the GIT_PATH is set correct.

Thanks.

**Comment by homebysix** [comment]
OK, I tried it again and it worked fine. Must have been too fast on the clicks before, I guess.

**Pull request merged**
